title: Blog do Rafael
description: Meu blog pessoal. Aqui falo sobre tecnologia, games retrô e tutoriais e tudo o que me der na telha!
author: Rafael Zenaro de Oliveira
baseurl: ""
url: "https://zenaror.github.io"
lang: "pt-BR"
theme: minima
excerpt_separator: <!--more-->
markdown: kramdown
permalink: /:year/:month/:day/:title
timezone: America/Sao_Paulo
paginate: 5  # Quantidade de posts por página
paginate_path: "/page:num/"
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-json-feed
  - jekyll-paginate
  - jekyll-sitemap
