title: Blog do Rafael
description: Meu blog pessoal
author: Rafael Zenaro de Oliveira
baseurl: ""
url: "https://zenaror.github.io"
theme: minima
markdown: kramdown
paginate: 5  # Quantidade de posts por página
paginate_path: "/page:num/"
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-json-feed
  - jekyll-paginate
