title: Blog do Rafael
description: Meu blog pessoal com visual retrô anos 2000
baseurl: ""
url: "https://seuusuario.github.io"
theme: minima
markdown: kramdown
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-json-feed

