title: Blog do Rafael
description: Meu blog pessoal
author: Rafael Zenaro de Oliveira
baseurl: ""
url: "https://zenaror.github.io"
theme: minima
markdown: kramdown
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-json-feed

